# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilogram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
